### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by HaozhongMa** [SamGa3/microbiome_reconstruction#3]
During the execution of step 5, we encountered a problem: 
processing file: sample_selection.Rmd
  |.....................................                                                  |  43% [data]                 
Quitting from lines 26-40 [data] (sample_selection.Rmd)
Error in `which()`:
! 参数'which'必需是逻辑值
Backtrace:
 1. global join_metadata(...)
 2. base::which(cont_column)
      at ../general_functions.R:282:9
![img1](https://github.com/SamGa3/microbiome_reconstruction/assets/66115097/d67185ed-272a-4055-8966-409f0596d127)

Then i saw ../general_functions.R:282:9 ,I found cont_column=NULL.
![img3](https://github.com/SamGa3/microbiome_reconstruction/assets/66115097/9beece90-2547-4269-b130-760e988fe3a2)

 Kindly provide insight on the potential cause of the problem!

**Comment by SamGa3** [comment]
Hi HaozhongMa,

I've been looking into the issue you reported, but I'm unable to reproduce the error inside my docker container. Are you running the scripts outside of it?
It seems that the lines of code you highlighted might be the cause of the issue, since in newer R versions, when "cont_column" is fulfilled in the for loop, it becomes a list instead of a vector. Consequently, the subsequent for loop fails to recognize "cont_column" as logical.
To address this, I've added a line that should resolve the problem outside my docker container. However, it's possible you may encounter similar issues throughout the workflow.

Please let me know if the problem persists or if you have any further questions.

Best,
Gaia

**Comment by HaozhongMa** [comment]
Hi Gaia,

Thank you for investigating the issue I reported. Indeed, I am running the scripts outside of a docker container, which might explain the discrepancy in our results.

Your explanation regarding the behavior of "cont_column" in newer R versions clarifies a lot. I suspected it might be a version-specific issue. The fact that "cont_column" is treated as a list instead of a vector in newer versions indeed be the root of the problem.

I appreciate your efforts in adding a line to the code to resolve this. I'll test the updated script in my environment and monitor if similar issues occur elsewhere in the workflow. I'll be sure to reach out if I encounter any further problems or if the issue persists.

Thank you once again for your prompt and detailed response. Your assistance is invaluable.

Best regards,
Haozhong Ma

**Comment by HaozhongMa** [comment]
Dear Gaia:
Thank you very much for your patience. I am currently replicating your results inside the docker container, and under your guidance, we have reached step 12. During the execution of step 12:
"humann --input data/RNAseq/humann_output/example/merged_fastq_out.fastq --output data/RNAseq/humann_output/example", 
I encountered the following error messages:

![error](https://github.com/SamGa3/microbiome_reconstruction/assets/66115097/2b66239b-9080-4910-b037-e9ee6651e0ad)

I would like to understand how to resolve these issues, especially regarding the failure to download the database file. Additionally, if there is a need to install a specific version of the Biom Python library or other configurations, please advise.

Thank you very much for your assistance!

Best regards,
Haozhong Ma

**Comment by SamGa3** [comment]
Dear Haozhong Ma,

As you have observed, the TCGA metadata I utilized for this project is not directly available on TCGA or GDC. Instead, it is a summary of the available information from GDC API, you can find an overview of available fields here https://docs.gdc.cancer.gov/API/Users_Guide/Appendix_A_Available_Fields/ . Additionally, detailed information about the usage of the API can be found here https://docs.gdc.cancer.gov/API/Users_Guide/Search_and_Retrieval/ .

To address the potential redundancy in some TCGA barcodes (resulting from samples being analyzed multiple times), I opted to identify each file using the GDC file id. Please note that GDC recently updated the files using a newer protocol, resulting in different file ids. To match the current files to the ones I used, you can use TCGA barcodes or download the manifest from this link https://github.com/NCI-GDC/gdc-docs/blob/develop/docs/Data/Release_Notes/GCv36_Manifests/ . The old files are no longer available.

The remaining metadata were sourced from previously published studies. If you have specific files in mind, could you please specify which ones you are interested in?

Best regards,
Gaia

P.S. I noticed that you closed your previous question. Although I couldn't reproduce the problem you encountered, I did encounter errors when Humann attempted to download its repositories. Unfortunately, I have limited control over this aspect. I hope you were able to find a solution, anyway this step was non-trivial for reproducing the results of the paper.
