### ISSUE TITLE
pathseq reference data

### ISSUE THREAD

**Issue by moxgreen** [SamGa3/microbiome_reconstruction#5]
Dear SamGa3,
do you dowloaded the required reference data from GATK? 
E.g. gs://gatk-best-practices/pathseq/resources/pathseq_microbe.tar.gz

**Comment by SamGa3** [comment]
Hi Moxgreen,

Yes, they now store the data in the Google Cloud here: https://console.cloud.google.com/storage/browser/gcp-public-data--broad-references/hg38/v0/CrossSpeciesContamination;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

You can find the microbial reference in the CrossSpeciesContaminant folder, and the standard human references are stored in the CrossSpeciesHuman folder.

Best,
Gaia
